# Generated by Django 3.2 on 2024-03-03 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка имеет границы от 1 до 10'), django.core.validators.MaxValueValidator(10, message='Оценка имеет границы от 1 до 10')]),
        ),
    ]
